### ISSUE TITLE
What's the difference between DEVINTERFACE_USB_DEVICE and WinUSB?

### ISSUE THREAD

**Issue by bglmmz** [MelbourneDeveloper/Device.Net#23]
I noticed there are 3 type devices defined in  WindowsDeviceConstants.cs
```
public static Guid GUID_DEVINTERFACE_HID = new Guid("4D1E55B2-F16F-11CF-88CB-001111000030");
public static Guid GUID_DEVINTERFACE_USB_DEVICE = new Guid("A5DCBF10-6530-11D2-901F-00C04FB951ED");
public static Guid WinUSBGuid = new Guid("dee824ef-729b-4a0e-9c14-b7117d33a817");
```

So,  what's the difference between DEVINTERFACE_USB_DEVICE  and WinUSB?

**Comment by bglmmz** [comment]
I listed out my HID devices by hidtest.exe, and I applied one as  either DeviceType.Hid or DeviceType.Usb into WindowsSample.program.cs，the method SetupDiEnumDeviceInterfaces() returned 259 error code in WindowsDeviceFactoryBase.cs.

**Comment by MelbourneDeveloper** [comment]
Excellent question @bglmmz 

The error you are seeing is probably this error: https://github.com/MelbourneDeveloper/Device.Net/issues/21 or related to it. This has been fixed to some extent in the latest version of the code. At least, it won't error. I haven't put out a new NuGet yet because there are big enhancements scheduled for next release and I need to test thoroughly (https://github.com/MelbourneDeveloper/Device.Net/projects/1).

Here is the documentation for GUID_DEVINTERFACE_USB_DEVICE.
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-usb-device

Unfortunately, I haven't had any luck with this Guid. If I iterate through devices with this Guid, I get errors when attempting to connect to them. I've tried this on both classic Windows and UWP, and both have issues. My understanding is that if you want to communicate with a USB device on Windows, it must have w definition in winusb.inf (https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/automatic-installation-of-winusb). 

For completeness sake, here is the documentation for GUID_DEVINTERFACE_HID.
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/guid-devinterface-hid

If clone the latest code, run it on your machine, and are still getting errors, or not seeing your device, I could possibly remote on to your machine via a secure TeamViewer session and help to diagnose the problem.

**Comment by MelbourneDeveloper** [comment]
@bglmmz BTW 259 means that there are no more items. So, it must be that the code is hitting the end of an enumeration, but thinking that there are still items to go. Are you able to run the code from the Device.Net repo with break on all errors turned on, and then send me a screenshot of the exact line where it breaks? I can probably fix that.

**Comment by MelbourneDeveloper** [comment]
@bglmmz I would like to help you with this. Can I get some more information? Otherwise, I will be closing the issue soon...

**Comment by MelbourneDeveloper** [comment]
@bglmmz have you tried enumerating the devices again since version 2.3?

**Comment by st-arnold** [comment]
I just struggled with a problem where no USB devices at all were listed when using WinUSB GUID:

![image](https://user-images.githubusercontent.com/14167665/72359483-09f38e00-36f7-11ea-8b79-9f2bad526562.png)

After changing the GUID in WindowsDeviceFactoryBase.cs GetConnectedDeviceDefinitionsAsync

`                //var guidString = GetClassGuid().ToString();
                var guidString = WindowsDeviceConstants.GUID_DEVINTERFACE_USB_DEVICE.ToString();
`

now devices get listed:

![image](https://user-images.githubusercontent.com/14167665/72359578-30b1c480-36f7-11ea-9267-7f4732c20151.png)

Running on Windows Desktop (Win 10 Pro ver 1903, build 18362.535)
Usb.Net.WindowsSample but commented out HID and serial port device factories and enabled DebugLogger LogToConsole.

**Comment by MelbourneDeveloper** [comment]
@st-arnold thanks for letting me know. I'd be keen to know if you can connect to any of those devices. I've been able to enumerate them in the past, but I only get errors when I connect. If you can connect to one, I'll look at adding the guid to the library.
